version: '3'
services:
  frontend:
    container_name: dust_frontend
    image: devhenrycha/dust_frontend:${FRONTEND_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      # - $HOME/frontend:/app/dist/data
      # - /home/ubuntu/nginx/sites/sites-enabled:/etc/nginx/sites-enabled
    restart: unless-stopped
    
  backend:
    container_name: dust_backend
    image: devhenrycha/dust_backend:${BACKEND_TAG}
    ports:
      - "8081:8081"
    # volumes:

    environment:
    #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
        - SPRING_PROFILES_ACTIVE=server
    
    restart: unless-stopped
