version: '3'
services:
  frontend:
    container_name: dust_frontend
    image: dust_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    
  backend:
    container_name: dust_backend
    image: dust_backend
    ports:
      - "8081:8081"

    environment:
        - SPRING_PROFILES_ACTIVE=server
    
    restart: unless-stopped
