import { ISearchUser } from '../pages/Search/search-types'

export const dummy: ISearchUser[] = [
	{
		id: 1,
		profileImg: '/public/dummy/각도의-중요성-탁이.jpeg',
		userName: '각도가 중요한 탁이',
		level: 1,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 2,
		profileImg: '/public/dummy/방해꾼-길이.jpeg',
		userName: '방해 장인 길이',
		level: 2,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 3,
		profileImg: '/public/dummy/산탁.jpeg',
		userName: '산탁클로스',
		level: 5,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 4,
		profileImg: '/public/dummy/신난-길이.jpeg',
		userName: '신난당 길이',
		level: 2,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 5,
		profileImg: '/public/dummy/옆모습-탁이.jpeg',
		userName: '옆태 미남 탁이',
		level: 2,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 6,
		profileImg: '/public/dummy/예쁜-길이.jpeg',
		userName: '미묘 길이',
		level: 1,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 7,
		profileImg: '/public/dummy/으엥-길이.jpeg',
		userName: '으엥 놀란 길이',
		level: 3,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
	{
		id: 1,
		profileImg: '/public/dummy/턱살-탁이.jpeg',
		userName: '턱살이 좀 나온 탁이',
		level: 1,
		duplicateFollower: null,
		followCnt: 0,
		growth_point: 0,
		solved_cnt: 0,
	},
]
