spring:
  datasource:
    url: ENC(z36k0b1b/AfJu4cWy+xQDf0P/b5T4DvjlkyUlz/IpSdDFjOGX23ng3ZeOrvW4P3V31FcRzXoagyaD3eJYYm3CVzZfM6O/E5muzih4pC0HIwklAS3HkolUQ==)
    username: ENC(LUTCtJLqc+lZcOzKYAoPwg==)
    password: ENC(eYpBIDT4rRgreECNkq9uaA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
# Local DB PW Settings..
# 상수 : ENC(eYpBIDT4rRgreECNkq9uaA==)
# 정현 : ENC(KNbVzoEMOy6NFHEmtUFhMhTFTpsef8bH)

jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  sql:
    init:
      mode: always
# properties:
# hibernate:
# format_sql: true
springdoc:
  api-docs:
    enabled: true
    path: / api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  issuer: ENC(14Ooqgf/y/yIGDkfqCyTKJy3LG9Fpb/d0SydS0en9673xiV1HfACnA==)
  secret_key: ENC(7/o7yXVnICk0ep5F8NsM0MokqQtwmRYjDerggYrJ4OPZ4jnU8o7AjItfscf/bL/P)
