server:
    port: 8081
    servlet:
        context-path: /api
spring:
    profiles:
        active: local
        include: key

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
jpa:
    hibernate:
        ddl-auto: create
    show-sql: true
    sql:
        init:
            mode: always

jwt:
    issuer: ENC(14Ooqgf/y/yIGDkfqCyTKJy3LG9Fpb/d0SydS0en9673xiV1HfACnA==)
    secret_key: ENC(7/o7yXVnICk0ep5F8NsM0MokqQtwmRYjDerggYrJ4OPZ4jnU8o7AjItfscf/bL/P)

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: ${my-db.url}
        username: ${my-db.username}
        password: ${my-db.password}
        driver-class-name: ${my-db.driver-class-name}

---
spring:
    config:
        activate:
            on-profile: server
    datasource:
        url: ENC(6zXYvK+4jGgwy+iw3uzbvv8DiKK6Q1OkH0NNXqJAP6Mk6JMhvy0a4sLofAY2+QV2Ds7fTyTWmKAb7a6GQo74ii+TwFO25BECG7WgqXj3B28AJES4Jwg16g==)
        username: ENC(xqQCVTAfmYRmwZ9w2gdoSA==)
        password: ENC(18LUnOaoJHQYsMpduiIKDn34Xxr57/7n)
        driver-class-name: com.mysql.cj.jdbc.Driver